config:
  superlive:
    auth-value: ${AUTH_VALUE:dqkoimeT_qNak4E9Fl6DfKY_}
    host: ${HOST:http://merch.sp.tv}
    sdk-api: /api/server-sdk
    endpoints:
      host:
        index: /hosts
        count: ${config.superlive.endpoints.host.index}/count
        path-variable: ${config.superlive.endpoints.host.index}/{id}
      participant:
        index: /participants
        path-variable: ${config.superlive.endpoints.participant.index}/{id}
        gift-points: ${config.superlive.endpoints.participant.index}/{id}/credit/gift-point
      gift:
        index: /gifts
        packs: ${config.superlive.endpoints.gift.index}/packs
        path-variable: ${config.superlive.endpoints.gift.index}/{id}
        packs-path-variable: ${config.superlive.endpoints.gift.packs}/{id}
      sticker:
        index: /stickers
        packs: ${config.superlive.endpoints.sticker.index}/packs
        path-variable: ${config.superlive.endpoints.sticker.index}/{id}
        packs-path-variable: ${config.superlive.endpoints.sticker.packs}/{id}
      upload:
        index: /upload/file

  constants:
    auth-key: ${AUTH_KEY:Authorization}

webclient:
  duration:
    default: 30
    failsafe: 60