spring:
  main:
    banner-mode: off
    log-startup-info: false

superlive:
  configuration:
    merchant:
      authorization-value: ${AUTHORIZATION_KEY:dqkoimeT_qNak4E9Fl6DfKY_}
      host-id: ${HOST_ID:648693da5a508510f60625fb}
      host: ${HOST:http://merch.sp.tv/api/server-sdk}
      endpoints:
        hosts: ${superlive.configuration.merchant.host}/hosts
        counting: /count
        path-variable: /hosts/{id}
        participants: /participants

  constants:
    authorization-key: Authorization

webclient:
  duration:
    default: 30
    failsafe: 60